/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type HomepageVideo = {
  _id: string;
  _type: "homepageVideo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  youtubeId: string;
  sortOrder?: number;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Partner = {
  _id: string;
  _type: "partner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  logoDark?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  description?: PortableText;
  shortDescription?: string;
  website?: string;
  memberDiscount?: string;
  tier: "platinum" | "gold" | "silver" | "community";
  featured?: boolean;
  sortOrder?: number;
};

export type PortableText = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      caption?: string;
      _type: "image";
      _key: string;
    }
>;

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type TeamMemberReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "teamMember";
};

export type Program = {
  _id: string;
  _type: "program";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug: "photography" | "filmmaking" | "freediving" | "internship";
  name?: string;
  tag?: string;
  overline?: string;
  description?: string;
  shortDescription?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  panelImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  overviewImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  heroVideo?: string;
  fullDescription?: PortableText;
  highlights?: Array<string>;
  curriculum?: PortableText;
  instructor?: TeamMemberReference;
  gallery?: Gallery;
  faqs?: Array<
    {
      _key: string;
    } & Faq
  >;
  testimonials?: Array<
    {
      _key: string;
    } & Testimonial
  >;
  pricing?: PortableText;
  applicationOpen?: boolean;
  seoDescription?: string;
};

export type Gallery = {
  _type: "gallery";
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    caption?: string;
    _type: "image";
    _key: string;
  }>;
};

export type AcademyPageSettings = {
  _id: string;
  _type: "academyPageSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroEyebrow?: string;
  heroHeading?: string;
  ctaImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  ctaHeading?: string;
  ctaBody?: string;
  ctaButtonLabel?: string;
  detailApplyHeading?: string;
  detailApplyBody?: string;
  applyButtonLabel?: string;
};

export type FilmsPageSettings = {
  _id: string;
  _type: "filmsPageSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  showLatestRow?: boolean;
  showAllVideosRow?: boolean;
  heroEyebrow?: string;
  watchButtonLabel?: string;
  detailsButtonLabel?: string;
  catalogueHeading?: string;
  catalogueDescription?: string;
  featuredRowTitle?: string;
  latestRowTitle?: string;
  allFilmsRowTitle?: string;
};

export type FilmReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "film";
};

export type FilmCollection = {
  _id: string;
  _type: "filmCollection";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description?: string;
  films: Array<
    {
      _key: string;
    } & FilmReference
  >;
  sortOrder?: number;
  enabled?: boolean;
};

export type Film = {
  _id: string;
  _type: "film";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  tagline?: string;
  poster?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  backdrop?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  description?: PortableText;
  videoEmbed: string;
  credits?: Array<{
    role: string;
    teamMember?: TeamMemberReference;
    name?: string;
    externalLinks?: Array<{
      label: string;
      url: string;
      _key: string;
    }>;
    _key: string;
  }>;
  releaseYear?: number;
  duration?: string;
  status?: "published" | "in-production" | "coming-soon";
  locations?: Array<string>;
  subjects?: Array<string>;
  formats?: Array<string>;
  skills?: Array<string>;
  displayTags?: Array<string>;
  featured?: boolean;
  sortOrder?: number;
};

export type TeamMember = {
  _id: string;
  _type: "teamMember";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  title?: string;
  shortBio?: string;
  fullBio?: PortableText;
  specialties?: Array<string>;
  socialLinks?: Array<
    {
      _key: string;
    } & SocialLink
  >;
  featured?: boolean;
  sortOrder?: number;
};

export type Testimonial = {
  _type: "testimonial";
  quote: string;
  authorName: string;
  authorDetail?: string;
  authorImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
};

export type Faq = {
  _type: "faq";
  question: string;
  answer: PortableText;
};

export type SocialLink = {
  _type: "socialLink";
  platform:
    | "instagram"
    | "youtube"
    | "vimeo"
    | "tiktok"
    | "linkedin"
    | "website";
  url: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | HomepageVideo
  | SanityImageAssetReference
  | Partner
  | PortableText
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | TeamMemberReference
  | Program
  | Gallery
  | AcademyPageSettings
  | FilmsPageSettings
  | FilmReference
  | FilmCollection
  | Film
  | TeamMember
  | Testimonial
  | Faq
  | SocialLink
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/lib/sanity/queries.ts
// Variable: FILMS_QUERY
// Query: *[_type == "film" && defined(slug.current)] | order(sortOrder asc, releaseYear desc) {      _id,  title,  slug,  tagline,  videoEmbed,  duration,  releaseYear,  status,  featured,  sortOrder,  locations,  subjects,  formats,  skills,  displayTags,  poster,    backdrop  }
export type FILMS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: Slug;
  tagline: string | null;
  videoEmbed: string;
  duration: string | null;
  releaseYear: number | null;
  status: "coming-soon" | "in-production" | "published" | null;
  featured: boolean | null;
  sortOrder: number | null;
  locations: Array<string> | null;
  subjects: Array<string> | null;
  formats: Array<string> | null;
  skills: Array<string> | null;
  displayTags: Array<string> | null;
  poster: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  backdrop: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: FILM_BY_SLUG_QUERY
// Query: *[_type == "film" && slug.current == $slug][0] {    _id, title, slug, tagline, description, videoEmbed,    credits[]{      role,      name,      "teamMember": teamMember->{ _id, name, slug },      externalLinks[]{ label, url }    },    releaseYear, duration, status, featured, sortOrder,    locations, subjects, formats, skills, displayTags  }
export type FILM_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: Slug;
  tagline: string | null;
  description: PortableText | null;
  videoEmbed: string;
  credits: Array<{
    role: string;
    name: string | null;
    teamMember: {
      _id: string;
      name: string;
      slug: Slug;
    } | null;
    externalLinks: Array<{
      label: string;
      url: string;
    }> | null;
  }> | null;
  releaseYear: number | null;
  duration: string | null;
  status: "coming-soon" | "in-production" | "published" | null;
  featured: boolean | null;
  sortOrder: number | null;
  locations: Array<string> | null;
  subjects: Array<string> | null;
  formats: Array<string> | null;
  skills: Array<string> | null;
  displayTags: Array<string> | null;
} | null;

// Source: src/lib/sanity/queries.ts
// Variable: FEATURED_FILMS_QUERY
// Query: *[_type == "film" && featured == true && defined(slug.current)] | order(sortOrder asc) {      _id,  title,  slug,  tagline,  videoEmbed,  duration,  releaseYear,  status,  featured,  sortOrder,  locations,  subjects,  formats,  skills,  displayTags,  poster  }
export type FEATURED_FILMS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: Slug;
  tagline: string | null;
  videoEmbed: string;
  duration: string | null;
  releaseYear: number | null;
  status: "coming-soon" | "in-production" | "published" | null;
  featured: true;
  sortOrder: number | null;
  locations: Array<string> | null;
  subjects: Array<string> | null;
  formats: Array<string> | null;
  skills: Array<string> | null;
  displayTags: Array<string> | null;
  poster: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: HOMEPAGE_VIDEOS_QUERY
// Query: *[_type == "homepageVideo"] | order(sortOrder asc) {    _id,    title,    youtubeId  }
export type HOMEPAGE_VIDEOS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  youtubeId: string;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: FILM_COLLECTIONS_QUERY
// Query: *[_type == "filmCollection" && enabled == true] | order(sortOrder asc) {    _id,    title,    slug,    description,    sortOrder,    films[]->{        _id,  title,  slug,  tagline,  videoEmbed,  duration,  releaseYear,  status,  featured,  sortOrder,  locations,  subjects,  formats,  skills,  displayTags,  poster    }  }
export type FILM_COLLECTIONS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: Slug;
  description: string | null;
  sortOrder: number | null;
  films: Array<{
    _id: string;
    title: string;
    slug: Slug;
    tagline: string | null;
    videoEmbed: string;
    duration: string | null;
    releaseYear: number | null;
    status: "coming-soon" | "in-production" | "published" | null;
    featured: boolean | null;
    sortOrder: number | null;
    locations: Array<string> | null;
    subjects: Array<string> | null;
    formats: Array<string> | null;
    skills: Array<string> | null;
    displayTags: Array<string> | null;
    poster: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  }>;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: FILMS_PAGE_SETTINGS_QUERY
// Query: *[_type == "filmsPageSettings" && _id == "filmsPageSettings"][0] {    "showLatestRow": coalesce(showLatestRow, true),    "showAllVideosRow": coalesce(showAllVideosRow, true),    heroEyebrow,    watchButtonLabel,    detailsButtonLabel,    catalogueHeading,    catalogueDescription,    featuredRowTitle,    latestRowTitle,    allFilmsRowTitle  }
export type FILMS_PAGE_SETTINGS_QUERY_RESULT = {
  showLatestRow: boolean | true;
  showAllVideosRow: boolean | true;
  heroEyebrow: string | null;
  watchButtonLabel: string | null;
  detailsButtonLabel: string | null;
  catalogueHeading: string | null;
  catalogueDescription: string | null;
  featuredRowTitle: string | null;
  latestRowTitle: string | null;
  allFilmsRowTitle: string | null;
} | null;

// Source: src/lib/sanity/queries.ts
// Variable: ALL_FILM_SLUGS_QUERY
// Query: *[_type == "film" && defined(slug.current)].slug.current
export type ALL_FILM_SLUGS_QUERY_RESULT = Array<string>;

// Source: src/lib/sanity/queries.ts
// Variable: PROGRAM_BY_SLUG_QUERY
// Query: *[_type == "program" && slug == $slug][0] {    _id, slug, name, overline, shortDescription, description,    heroImage, panelImage, overviewImage, heroVideo, fullDescription, highlights,    curriculum, instructor->{ _id, name, slug, photo, title },    gallery, faqs, testimonials, pricing, seoDescription, applicationOpen  }
export type PROGRAM_BY_SLUG_QUERY_RESULT = {
  _id: string;
  slug: "filmmaking" | "freediving" | "internship" | "photography";
  name: string | null;
  overline: string | null;
  shortDescription: string | null;
  description: string | null;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  panelImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  } | null;
  overviewImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  } | null;
  heroVideo: string | null;
  fullDescription: PortableText | null;
  highlights: Array<string> | null;
  curriculum: PortableText | null;
  instructor: {
    _id: string;
    name: string;
    slug: Slug;
    photo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    } | null;
    title: string | null;
  } | null;
  gallery: Gallery | null;
  faqs: Array<
    {
      _key: string;
    } & Faq
  > | null;
  testimonials: Array<
    {
      _key: string;
    } & Testimonial
  > | null;
  pricing: PortableText | null;
  seoDescription: string | null;
  applicationOpen: boolean | null;
} | null;

// Source: src/lib/sanity/queries.ts
// Variable: ALL_PROGRAMS_CMS_QUERY
// Query: *[_type == "program"] {    _id, slug, name, tag, overline, description, highlights,    heroImage, panelImage, overviewImage, applicationOpen  }
export type ALL_PROGRAMS_CMS_QUERY_RESULT = Array<{
  _id: string;
  slug: "filmmaking" | "freediving" | "internship" | "photography";
  name: string | null;
  tag: string | null;
  overline: string | null;
  description: string | null;
  highlights: Array<string> | null;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  panelImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  } | null;
  overviewImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  } | null;
  applicationOpen: boolean | null;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: ACADEMY_PAGE_SETTINGS_QUERY
// Query: *[_type == "academyPageSettings" && _id == "academyPageSettings"][0] {    heroEyebrow, heroHeading, ctaImage, ctaHeading, ctaBody, ctaButtonLabel,    detailApplyHeading, detailApplyBody, applyButtonLabel  }
export type ACADEMY_PAGE_SETTINGS_QUERY_RESULT = {
  heroEyebrow: string | null;
  heroHeading: string | null;
  ctaImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  ctaHeading: string | null;
  ctaBody: string | null;
  ctaButtonLabel: string | null;
  detailApplyHeading: string | null;
  detailApplyBody: string | null;
  applyButtonLabel: string | null;
} | null;

// Source: src/lib/sanity/queries.ts
// Variable: TEAM_MEMBERS_QUERY
// Query: *[_type == "teamMember"] | order(sortOrder asc) {    _id, name, slug, photo, title, shortBio, specialties, socialLinks, featured  }
export type TEAM_MEMBERS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: Slug;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  } | null;
  title: string | null;
  shortBio: string | null;
  specialties: Array<string> | null;
  socialLinks: Array<
    {
      _key: string;
    } & SocialLink
  > | null;
  featured: boolean | null;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: ALL_TEAM_MEMBER_SLUGS_QUERY
// Query: *[_type == "teamMember" && defined(slug.current)].slug.current
export type ALL_TEAM_MEMBER_SLUGS_QUERY_RESULT = Array<string>;

// Source: src/lib/sanity/queries.ts
// Variable: TEAM_MEMBER_BY_SLUG_QUERY
// Query: *[_type == "teamMember" && slug.current == $slug][0] {    _id, name, slug, photo, title, shortBio, fullBio, specialties, socialLinks  }
export type TEAM_MEMBER_BY_SLUG_QUERY_RESULT = {
  _id: string;
  name: string;
  slug: Slug;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  } | null;
  title: string | null;
  shortBio: string | null;
  fullBio: PortableText | null;
  specialties: Array<string> | null;
  socialLinks: Array<
    {
      _key: string;
    } & SocialLink
  > | null;
} | null;

// Source: src/lib/sanity/queries.ts
// Variable: PARTNERS_QUERY
// Query: *[_type == "partner"] | order(sortOrder asc) {    _id, name, slug, logo, logoDark, description, shortDescription,    website, memberDiscount, tier, featured  }
export type PARTNERS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: Slug;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  } | null;
  logoDark: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  description: PortableText | null;
  shortDescription: string | null;
  website: string | null;
  memberDiscount: string | null;
  tier: "community" | "gold" | "platinum" | "silver";
  featured: boolean | null;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: FEATURED_PARTNERS_QUERY
// Query: *[_type == "partner" && featured == true] | order(sortOrder asc) {    _id, name, slug, logo, logoDark, shortDescription, website, memberDiscount  }
export type FEATURED_PARTNERS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: Slug;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  } | null;
  logoDark: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  shortDescription: string | null;
  website: string | null;
  memberDiscount: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "film" && defined(slug.current)] | order(sortOrder asc, releaseYear desc) {\n    \n  _id,\n  title,\n  slug,\n  tagline,\n  videoEmbed,\n  duration,\n  releaseYear,\n  status,\n  featured,\n  sortOrder,\n  locations,\n  subjects,\n  formats,\n  skills,\n  displayTags,\n  poster\n,\n    backdrop\n  }\n': FILMS_QUERY_RESULT;
    '\n  *[_type == "film" && slug.current == $slug][0] {\n    _id, title, slug, tagline, description, videoEmbed,\n    credits[]{\n      role,\n      name,\n      "teamMember": teamMember->{ _id, name, slug },\n      externalLinks[]{ label, url }\n    },\n    releaseYear, duration, status, featured, sortOrder,\n    locations, subjects, formats, skills, displayTags\n  }\n': FILM_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "film" && featured == true && defined(slug.current)] | order(sortOrder asc) {\n    \n  _id,\n  title,\n  slug,\n  tagline,\n  videoEmbed,\n  duration,\n  releaseYear,\n  status,\n  featured,\n  sortOrder,\n  locations,\n  subjects,\n  formats,\n  skills,\n  displayTags,\n  poster\n\n  }\n': FEATURED_FILMS_QUERY_RESULT;
    '\n  *[_type == "homepageVideo"] | order(sortOrder asc) {\n    _id,\n    title,\n    youtubeId\n  }\n': HOMEPAGE_VIDEOS_QUERY_RESULT;
    '\n  *[_type == "filmCollection" && enabled == true] | order(sortOrder asc) {\n    _id,\n    title,\n    slug,\n    description,\n    sortOrder,\n    films[]->{\n      \n  _id,\n  title,\n  slug,\n  tagline,\n  videoEmbed,\n  duration,\n  releaseYear,\n  status,\n  featured,\n  sortOrder,\n  locations,\n  subjects,\n  formats,\n  skills,\n  displayTags,\n  poster\n\n    }\n  }\n': FILM_COLLECTIONS_QUERY_RESULT;
    '\n  *[_type == "filmsPageSettings" && _id == "filmsPageSettings"][0] {\n    "showLatestRow": coalesce(showLatestRow, true),\n    "showAllVideosRow": coalesce(showAllVideosRow, true),\n    heroEyebrow,\n    watchButtonLabel,\n    detailsButtonLabel,\n    catalogueHeading,\n    catalogueDescription,\n    featuredRowTitle,\n    latestRowTitle,\n    allFilmsRowTitle\n  }\n': FILMS_PAGE_SETTINGS_QUERY_RESULT;
    '\n  *[_type == "film" && defined(slug.current)].slug.current\n': ALL_FILM_SLUGS_QUERY_RESULT;
    '\n  *[_type == "program" && slug == $slug][0] {\n    _id, slug, name, overline, shortDescription, description,\n    heroImage, panelImage, overviewImage, heroVideo, fullDescription, highlights,\n    curriculum, instructor->{ _id, name, slug, photo, title },\n    gallery, faqs, testimonials, pricing, seoDescription, applicationOpen\n  }\n': PROGRAM_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "program"] {\n    _id, slug, name, tag, overline, description, highlights,\n    heroImage, panelImage, overviewImage, applicationOpen\n  }\n': ALL_PROGRAMS_CMS_QUERY_RESULT;
    '\n  *[_type == "academyPageSettings" && _id == "academyPageSettings"][0] {\n    heroEyebrow, heroHeading, ctaImage, ctaHeading, ctaBody, ctaButtonLabel,\n    detailApplyHeading, detailApplyBody, applyButtonLabel\n  }\n': ACADEMY_PAGE_SETTINGS_QUERY_RESULT;
    '\n  *[_type == "teamMember"] | order(sortOrder asc) {\n    _id, name, slug, photo, title, shortBio, specialties, socialLinks, featured\n  }\n': TEAM_MEMBERS_QUERY_RESULT;
    '\n  *[_type == "teamMember" && defined(slug.current)].slug.current\n': ALL_TEAM_MEMBER_SLUGS_QUERY_RESULT;
    '\n  *[_type == "teamMember" && slug.current == $slug][0] {\n    _id, name, slug, photo, title, shortBio, fullBio, specialties, socialLinks\n  }\n': TEAM_MEMBER_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "partner"] | order(sortOrder asc) {\n    _id, name, slug, logo, logoDark, description, shortDescription,\n    website, memberDiscount, tier, featured\n  }\n': PARTNERS_QUERY_RESULT;
    '\n  *[_type == "partner" && featured == true] | order(sortOrder asc) {\n    _id, name, slug, logo, logoDark, shortDescription, website, memberDiscount\n  }\n': FEATURED_PARTNERS_QUERY_RESULT;
  }
}
