/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Partner = {
  _id: string;
  _type: "partner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  logoDark?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  description?: PortableText;
  shortDescription?: string;
  website?: string;
  memberDiscount?: string;
  tier: "platinum" | "gold" | "silver" | "community";
  featured?: boolean;
  sortOrder?: number;
};

export type PortableText = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      caption?: string;
      _type: "image";
      _key: string;
    }
>;

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type TeamMemberReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "teamMember";
};

export type Program = {
  _id: string;
  _type: "program";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug: "photography" | "filmmaking" | "freediving" | "internship";
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  heroVideo?: string;
  fullDescription?: PortableText;
  highlights?: Array<string>;
  curriculum?: PortableText;
  instructor?: TeamMemberReference;
  gallery?: Gallery;
  faqs?: Array<
    {
      _key: string;
    } & Faq
  >;
  testimonials?: Array<
    {
      _key: string;
    } & Testimonial
  >;
  pricing?: PortableText;
  applicationOpen?: boolean;
  seoDescription?: string;
};

export type Gallery = {
  _type: "gallery";
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    caption?: string;
    _type: "image";
    _key: string;
  }>;
};

export type TeamMember = {
  _id: string;
  _type: "teamMember";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  role: "founder" | "instructor" | "guide";
  title?: string;
  shortBio?: string;
  fullBio?: PortableText;
  specialties?: Array<string>;
  socialLinks?: Array<
    {
      _key: string;
    } & SocialLink
  >;
  featured?: boolean;
  sortOrder?: number;
};

export type Film = {
  _id: string;
  _type: "film";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  tagline?: string;
  description?: PortableText;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  videoEmbed?: string;
  gallery?: Gallery;
  credits?: Array<{
    role: string;
    name: string;
    _key: string;
  }>;
  releaseYear?: number;
  duration?: string;
  status?: "published" | "in-production" | "coming-soon";
  featured?: boolean;
  sortOrder?: number;
};

export type Testimonial = {
  _type: "testimonial";
  quote: string;
  authorName: string;
  authorDetail?: string;
  authorImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
};

export type Faq = {
  _type: "faq";
  question: string;
  answer: PortableText;
};

export type SocialLink = {
  _type: "socialLink";
  platform:
    | "instagram"
    | "youtube"
    | "vimeo"
    | "tiktok"
    | "linkedin"
    | "website";
  url: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Partner
  | PortableText
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | TeamMemberReference
  | Program
  | Gallery
  | TeamMember
  | Film
  | Testimonial
  | Faq
  | SocialLink
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/lib/sanity/queries.ts
// Variable: FILMS_QUERY
// Query: *[_type == "film"] | order(sortOrder asc, releaseYear desc) {    _id, title, slug, tagline, heroImage, duration, releaseYear, status, featured  }
export type FILMS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: Slug;
  tagline: string | null;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  duration: string | null;
  releaseYear: number | null;
  status: "coming-soon" | "in-production" | "published" | null;
  featured: boolean | null;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: FILM_BY_SLUG_QUERY
// Query: *[_type == "film" && slug.current == $slug][0] {    _id, title, slug, tagline, description, heroImage, videoEmbed,    gallery, credits, releaseYear, duration, status  }
export type FILM_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: Slug;
  tagline: string | null;
  description: PortableText | null;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  videoEmbed: string | null;
  gallery: Gallery | null;
  credits: Array<{
    role: string;
    name: string;
    _key: string;
  }> | null;
  releaseYear: number | null;
  duration: string | null;
  status: "coming-soon" | "in-production" | "published" | null;
} | null;

// Source: src/lib/sanity/queries.ts
// Variable: FEATURED_FILMS_QUERY
// Query: *[_type == "film" && featured == true] | order(sortOrder asc) {    _id, title, slug, tagline, heroImage, duration, releaseYear  }
export type FEATURED_FILMS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: Slug;
  tagline: string | null;
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  duration: string | null;
  releaseYear: number | null;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: ALL_FILM_SLUGS_QUERY
// Query: *[_type == "film" && defined(slug.current)].slug.current
export type ALL_FILM_SLUGS_QUERY_RESULT = Array<string>;

// Source: src/lib/sanity/queries.ts
// Variable: PROGRAM_BY_SLUG_QUERY
// Query: *[_type == "program" && slug == $slug][0] {    _id, slug, heroImage, heroVideo, fullDescription, highlights,    curriculum, instructor->{ _id, name, slug, photo, role, title },    gallery, faqs, testimonials, pricing, seoDescription, applicationOpen  }
export type PROGRAM_BY_SLUG_QUERY_RESULT = {
  _id: string;
  slug: "filmmaking" | "freediving" | "internship" | "photography";
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  heroVideo: string | null;
  fullDescription: PortableText | null;
  highlights: Array<string> | null;
  curriculum: PortableText | null;
  instructor: {
    _id: string;
    name: string;
    slug: Slug;
    photo: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      _type: "image";
    } | null;
    role: "founder" | "guide" | "instructor";
    title: string | null;
  } | null;
  gallery: Gallery | null;
  faqs: Array<
    {
      _key: string;
    } & Faq
  > | null;
  testimonials: Array<
    {
      _key: string;
    } & Testimonial
  > | null;
  pricing: PortableText | null;
  seoDescription: string | null;
  applicationOpen: boolean | null;
} | null;

// Source: src/lib/sanity/queries.ts
// Variable: ALL_PROGRAMS_CMS_QUERY
// Query: *[_type == "program"] {    _id, slug, heroImage, applicationOpen  }
export type ALL_PROGRAMS_CMS_QUERY_RESULT = Array<{
  _id: string;
  slug: "filmmaking" | "freediving" | "internship" | "photography";
  heroImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  } | null;
  applicationOpen: boolean | null;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: TEAM_MEMBERS_QUERY
// Query: *[_type == "teamMember"] | order(sortOrder asc) {    _id, name, slug, photo, role, title, shortBio, specialties, socialLinks, featured  }
export type TEAM_MEMBERS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: Slug;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  } | null;
  role: "founder" | "guide" | "instructor";
  title: string | null;
  shortBio: string | null;
  specialties: Array<string> | null;
  socialLinks: Array<
    {
      _key: string;
    } & SocialLink
  > | null;
  featured: boolean | null;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: ALL_TEAM_MEMBER_SLUGS_QUERY
// Query: *[_type == "teamMember" && defined(slug.current)].slug.current
export type ALL_TEAM_MEMBER_SLUGS_QUERY_RESULT = Array<string>;

// Source: src/lib/sanity/queries.ts
// Variable: TEAM_MEMBER_BY_SLUG_QUERY
// Query: *[_type == "teamMember" && slug.current == $slug][0] {    _id, name, slug, photo, role, title, shortBio, fullBio, specialties, socialLinks  }
export type TEAM_MEMBER_BY_SLUG_QUERY_RESULT = {
  _id: string;
  name: string;
  slug: Slug;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  } | null;
  role: "founder" | "guide" | "instructor";
  title: string | null;
  shortBio: string | null;
  fullBio: PortableText | null;
  specialties: Array<string> | null;
  socialLinks: Array<
    {
      _key: string;
    } & SocialLink
  > | null;
} | null;

// Source: src/lib/sanity/queries.ts
// Variable: PARTNERS_QUERY
// Query: *[_type == "partner"] | order(sortOrder asc) {    _id, name, slug, logo, logoDark, description, shortDescription,    website, memberDiscount, tier, featured  }
export type PARTNERS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: Slug;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  } | null;
  logoDark: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  description: PortableText | null;
  shortDescription: string | null;
  website: string | null;
  memberDiscount: string | null;
  tier: "community" | "gold" | "platinum" | "silver";
  featured: boolean | null;
}>;

// Source: src/lib/sanity/queries.ts
// Variable: FEATURED_PARTNERS_QUERY
// Query: *[_type == "partner" && featured == true] | order(sortOrder asc) {    _id, name, slug, logo, logoDark, shortDescription, website, memberDiscount  }
export type FEATURED_PARTNERS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: Slug;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  } | null;
  logoDark: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  shortDescription: string | null;
  website: string | null;
  memberDiscount: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "film"] | order(sortOrder asc, releaseYear desc) {\n    _id, title, slug, tagline, heroImage, duration, releaseYear, status, featured\n  }\n': FILMS_QUERY_RESULT;
    '\n  *[_type == "film" && slug.current == $slug][0] {\n    _id, title, slug, tagline, description, heroImage, videoEmbed,\n    gallery, credits, releaseYear, duration, status\n  }\n': FILM_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "film" && featured == true] | order(sortOrder asc) {\n    _id, title, slug, tagline, heroImage, duration, releaseYear\n  }\n': FEATURED_FILMS_QUERY_RESULT;
    '\n  *[_type == "film" && defined(slug.current)].slug.current\n': ALL_FILM_SLUGS_QUERY_RESULT;
    '\n  *[_type == "program" && slug == $slug][0] {\n    _id, slug, heroImage, heroVideo, fullDescription, highlights,\n    curriculum, instructor->{ _id, name, slug, photo, role, title },\n    gallery, faqs, testimonials, pricing, seoDescription, applicationOpen\n  }\n': PROGRAM_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "program"] {\n    _id, slug, heroImage, applicationOpen\n  }\n': ALL_PROGRAMS_CMS_QUERY_RESULT;
    '\n  *[_type == "teamMember"] | order(sortOrder asc) {\n    _id, name, slug, photo, role, title, shortBio, specialties, socialLinks, featured\n  }\n': TEAM_MEMBERS_QUERY_RESULT;
    '\n  *[_type == "teamMember" && defined(slug.current)].slug.current\n': ALL_TEAM_MEMBER_SLUGS_QUERY_RESULT;
    '\n  *[_type == "teamMember" && slug.current == $slug][0] {\n    _id, name, slug, photo, role, title, shortBio, fullBio, specialties, socialLinks\n  }\n': TEAM_MEMBER_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "partner"] | order(sortOrder asc) {\n    _id, name, slug, logo, logoDark, description, shortDescription,\n    website, memberDiscount, tier, featured\n  }\n': PARTNERS_QUERY_RESULT;
    '\n  *[_type == "partner" && featured == true] | order(sortOrder asc) {\n    _id, name, slug, logo, logoDark, shortDescription, website, memberDiscount\n  }\n': FEATURED_PARTNERS_QUERY_RESULT;
  }
}
