import type {
  ShopProductWithVariants,
  ShopShippingZoneWithRates,
} from "@/lib/shop/types";
import {
  MOCK_SHOP_PRODUCT_ID,
  MOCK_SHOP_VARIANT_HOODIE_L_ID,
  MOCK_SHOP_VARIANT_HOODIE_M_ID,
} from "./mock-product-ids";

const MOCK_TIMESTAMP = "2026-05-08T00:00:00.000Z";

export const MOCK_SHOP_PRODUCT: ShopProductWithVariants = {
  id: MOCK_SHOP_PRODUCT_ID,
  title: "Mock BTM Freedive Hoodie",
  slug: "mock-btm-freedive-hoodie",
  type: "physical",
  status: "active",
  visibility: "public",
  purchase_access: "members",
  short_description:
    "Mock preview product for checking the store layout with real-looking content.",
  content_blocks: [
    {
      type: "rich_text",
      body: "This is a mock catalog item used to preview the storefront, product detail layout, pricing, media, and member checkout messaging before real inventory is entered.",
    },
    {
      type: "bullets",
      title: "Preview details",
      items: [
        "Heavyweight organic cotton blend",
        "Relaxed unisex fit with embroidered BTM mark",
        "Ships from Portugal in the launch flow",
      ],
    },
    {
      type: "specs",
      rows: [
        { label: "Material", value: "Mock 420gsm cotton fleece" },
        { label: "Color", value: "Deep black with bone logo" },
        { label: "Fulfillment", value: "Physical product with flat-rate shipping" },
      ],
    },
  ],
  stripe_tax_code: "txcd_99999999",
  tax_behavior: "exclusive",
  requires_shipping: true,
  requires_customer_notes: false,
  customer_notes_label: "Order notes",
  sort_order: 0,
  created_at: MOCK_TIMESTAMP,
  updated_at: MOCK_TIMESTAMP,
  variants: [
    {
      id: MOCK_SHOP_VARIANT_HOODIE_M_ID,
      product_id: MOCK_SHOP_PRODUCT_ID,
      title: "Black / M",
      sku: "MOCK-BTM-HOODIE-BLK-M",
      price_cents: 7900,
      currency: "eur",
      stripe_tax_code: "txcd_99999999",
      tax_behavior: "exclusive",
      track_inventory: true,
      stock_quantity: 12,
      low_stock_threshold: 3,
      active: true,
      sort_order: 0,
      created_at: MOCK_TIMESTAMP,
      updated_at: MOCK_TIMESTAMP,
    },
    {
      id: MOCK_SHOP_VARIANT_HOODIE_L_ID,
      product_id: MOCK_SHOP_PRODUCT_ID,
      title: "Black / L",
      sku: "MOCK-BTM-HOODIE-BLK-L",
      price_cents: 7900,
      currency: "eur",
      stripe_tax_code: "txcd_99999999",
      tax_behavior: "exclusive",
      track_inventory: true,
      stock_quantity: 8,
      low_stock_threshold: 3,
      active: true,
      sort_order: 1,
      created_at: MOCK_TIMESTAMP,
      updated_at: MOCK_TIMESTAMP,
    },
  ],
  media: [
    {
      id: "00000000-0000-4000-8000-000000000021",
      product_id: MOCK_SHOP_PRODUCT_ID,
      storage_path: "mock-shop-product.png",
      public_url: "/mock-shop-product.png",
      alt_text: "Mock black Behind The Mask hoodie product image",
      caption: "Mock product image",
      mime_type: "image/png",
      size_bytes: 62324,
      width: 1200,
      height: 1200,
      is_primary: true,
      sort_order: 0,
      created_at: MOCK_TIMESTAMP,
      updated_at: MOCK_TIMESTAMP,
    },
    {
      id: "00000000-0000-4000-8000-000000000022",
      product_id: MOCK_SHOP_PRODUCT_ID,
      storage_path: "mock-shop-product.png",
      public_url: "/mock-shop-product.png",
      alt_text: "Mock hoodie front detail",
      caption: "Mock front detail",
      mime_type: "image/png",
      size_bytes: 62324,
      width: 1200,
      height: 1200,
      is_primary: false,
      sort_order: 1,
      created_at: MOCK_TIMESTAMP,
      updated_at: MOCK_TIMESTAMP,
    },
    {
      id: "00000000-0000-4000-8000-000000000023",
      product_id: MOCK_SHOP_PRODUCT_ID,
      storage_path: "mock-shop-product.png",
      public_url: "/mock-shop-product.png",
      alt_text: "Mock hoodie packaging preview",
      caption: "Mock packaging preview",
      mime_type: "image/png",
      size_bytes: 62324,
      width: 1200,
      height: 1200,
      is_primary: false,
      sort_order: 2,
      created_at: MOCK_TIMESTAMP,
      updated_at: MOCK_TIMESTAMP,
    },
  ],
};

export const MOCK_SHOP_SHIPPING_ZONES: ShopShippingZoneWithRates[] = [
  {
    id: "00000000-0000-4000-8000-000000000031",
    name: "Portugal",
    slug: "mock-portugal",
    allowed_countries: ["PT"],
    active: true,
    sort_order: 0,
    created_at: MOCK_TIMESTAMP,
    updated_at: MOCK_TIMESTAMP,
    rates: [
      {
        id: "00000000-0000-4000-8000-000000000041",
        zone_id: "00000000-0000-4000-8000-000000000031",
        name: "Standard tracked shipping",
        description: "Mock tracked shipping within Portugal.",
        price_cents: 500,
        currency: "eur",
        stripe_tax_code: null,
        tax_behavior: "exclusive",
        active: true,
        sort_order: 0,
        created_at: MOCK_TIMESTAMP,
        updated_at: MOCK_TIMESTAMP,
      },
    ],
  },
  {
    id: "00000000-0000-4000-8000-000000000032",
    name: "European Union",
    slug: "mock-european-union",
    allowed_countries: ["ES", "FR", "DE", "IT", "NL", "BE", "IE"],
    active: true,
    sort_order: 1,
    created_at: MOCK_TIMESTAMP,
    updated_at: MOCK_TIMESTAMP,
    rates: [
      {
        id: "00000000-0000-4000-8000-000000000042",
        zone_id: "00000000-0000-4000-8000-000000000032",
        name: "EU tracked shipping",
        description: "Mock tracked shipping to common EU launch countries.",
        price_cents: 1200,
        currency: "eur",
        stripe_tax_code: null,
        tax_behavior: "exclusive",
        active: true,
        sort_order: 0,
        created_at: MOCK_TIMESTAMP,
        updated_at: MOCK_TIMESTAMP,
      },
    ],
  },
  {
    id: "00000000-0000-4000-8000-000000000033",
    name: "International",
    slug: "mock-international",
    allowed_countries: ["GB", "US", "CA", "AU", "JP"],
    active: true,
    sort_order: 2,
    created_at: MOCK_TIMESTAMP,
    updated_at: MOCK_TIMESTAMP,
    rates: [
      {
        id: "00000000-0000-4000-8000-000000000043",
        zone_id: "00000000-0000-4000-8000-000000000033",
        name: "International tracked shipping",
        description: "Mock tracked shipping for wider preview countries.",
        price_cents: 2400,
        currency: "eur",
        stripe_tax_code: null,
        tax_behavior: "exclusive",
        active: true,
        sort_order: 0,
        created_at: MOCK_TIMESTAMP,
        updated_at: MOCK_TIMESTAMP,
      },
    ],
  },
];

export function shouldShowMockShopProduct() {
  return process.env.NEXT_PUBLIC_SHOW_MOCK_SHOP_PRODUCT === "1";
}
